package repl
import (
	"unicode"
	"bufio"
	"io"
	"fmt"
	"strings"
	"github.com/CoupDeGrace92/pokedexcli/commands"
	"github.com/CoupDeGrace92/pokedexcli/state"
)

func CleanInput(text string) []string {
	cleanedInput := []string{}
	lowerText := strings.ToLower(text)
	currentWord := ""
	for _, char := range lowerText{
		if unicode.IsSpace(rune(char)){
			if currentWord != ""{
				cleanedInput = append(cleanedInput, currentWord)
			}
			currentWord = ""
			continue
		}
		currentWord += string(char)
	}
	if currentWord != ""{
		cleanedInput = append(cleanedInput, currentWord)
	}
	
	return cleanedInput
}

func CommandReader(reader io.Reader, cfg *state.Config) {
	scanner := bufio.NewScanner(reader)
	for {
		fmt.Print("Pokedex > ")
		scan := scanner.Scan() //First advances then scanner then should be a bool that returns false when there are no more tokens to scan, Scanner.Err method will return any error that occurred during scanning
		if err := scanner.Err(); err != nil {
			fmt.Printf("Invalid input: %s", err)
		}
		if scan == false {
			fmt.Printf("No data was entered")
		}

		textScan := scanner.Text() //String holding the bytes of the most recent token generated by Scanner.Scan
		value := strings.Fields(textScan)
		primary := value[0]
		var args []string
		if len(value)>1{
			args=value[1:]
		}
		command, ok := cmd.SupportedCommands[primary]
		if !ok {
			fmt.Printf("Command %s not found in Supported Commands, try help to see supported commands\n", textScan)
			continue
		} 
		command.Callback(cfg, args...)
	}
}

func bufReaderOneLoop(reader io.Reader) string {
	scanner := bufio.NewScanner(reader)
	fmt.Print("Pokedex > ")
	scan := scanner.Scan() //First advances then scanner then should be a bool that returns false when there are no more tokens to scan, Scanner.Err method will return any error that occurred during scanning
	if err := scanner.Err(); err != nil {
		fmt.Printf("Invalid input: %s", err)
		return ""
	}
	if scan == false {
		fmt.Printf("No data was entered")
		return ""
	}

	textScan := scanner.Text() //String holding the bytes of the most recent token generated by Scanner.Scan
	textScanSlice := CleanInput(textScan)
	firstWord := textScanSlice[0]
	fmt.Printf("Your command was: %s\n", firstWord)
	return firstWord
}